import { Box, useColorMode } from "@chakra-ui/react";
import Head from "next/head";
import { useEffect } from "react";
import Footer from "./components/Footer";
import Navbar from "./components/Navbar";
import AppContextProvider from "./context/AppContext";

export default function Root({ children }: any) {
  const { toggleColorMode, colorMode } = useColorMode();

  useEffect(() => {
    if (colorMode === "dark") toggleColorMode();
  }, [])

  return (
    <>
      <AppContextProvider>
        <Head>
          <title>Elf Next Door</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <Box minH="100vh">
          <Navbar />
          {children}
          <Footer />
        </Box>
      </AppContextProvider>
    </>
  )
}